### ISSUE TITLE
ch13fd357r0y3r - Withdrawal transaction can be proven on In-Progress Game Status.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-optimism-2024-judging#121]
ch13fd357r0y3r

medium

# Withdrawal transaction can be proven on In-Progress Game Status.

## Summary
A withdrawal transaction can be proven through `proveWithdrawalTransaction(...)`. It only allows proving and finalizing TX when the dispute game proxy status is in favor of the defender.

This report showcases that an invalid game status is allowed in proving transactions.

## Vulnerability Detail
There is a missing check on the `proveWithdrawalTransaction(...)` function where it does allow IN-Progress Game Status to be proven. 

Upon analyzing the `proveWithdrawalTransaction(...)` it does not allow for proving withdrawals against dispute games that have resolved against the favor of the root claim.

```solidity
    function proveWithdrawalTransaction(
        Types.WithdrawalTransaction memory _tx,
        uint256 _disputeGameIndex,
        Types.OutputRootProof calldata _outputRootProof,
        bytes[] calldata _withdrawalProof
    )
        external
        whenNotPaused
    {
        ......
        require(
            gameProxy.status() != GameStatus.CHALLENGER_WINS,
            "OptimismPortal: cannot prove against invalid dispute games"
        );
      .......
     }
```

Those require condition are missing `GameStatus.IN_PROGRESS`. Technically, it allows the invalid or unknown results of the dispute games to be proven.

## Impact
A transaction's root claim with an invalid game status can be proven successfully. 

## Code Snippet
https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/L1/OptimismPortal2.sol#L242-L325

## Tool used

Manual Review

## Recommendation
Consider updating those checks against invalid dispute games.
Pseudocode:
```solidity
        require(
            gameProxy.status() != GameStatus.CHALLENGER_WINS && gameProxy.status() != GameStatus.IN_PROGRESS,
            "OptimismPortal: cannot prove against invalid dispute games"
        );
```

**Comment by shanb1605** [comment]
@nevillehuang @smartcontracts 
This report argues only to fix the `proveWithdrawalTransaction` on OptimismPortal2. The check needs to be implemented to prevent proving `IN_PROGRESS` games on OptimismPortal2

**Comment by sherlock-admin2** [comment]
> Escalate
> This report argues only to fix the `proveWithdrawalTransaction` on OptimismPortal2. The check needs to be implemented to prevent proving `IN_PROGRESS` games on OptimismPortal2

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by 0xlastByte** [comment]
i agree with the report because the default status of gameProxy.status() is IN_PROGRESS check this issue https://github.com/sherlock-audit/2024-02-optimism-2024-judging/issues/241

**Comment by shanb1605** [comment]
@smartcontracts please verify this issue whether it's valid or not 😢

**Comment by 0xlastByte** [comment]
Escalate

I believe the finding to be valid:

1)  the finding is valid because the creation of DisputeGame is done via [create function](https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/DisputeGameFactory.sol#L84-L122) and then stores the new created DisputeGame in [_disputeGameList.push(id);](https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/DisputeGameFactory.sol#L120) array and Since the Default Status of gameProxy is IN_PROGRESS the Withdrawal transaction can be proven on In-Progress Game Status. as it is described in the issue.

**Comment by 0xlastByte** [comment]
@smartcontracts @nevillehuang  

I believe the finding to be valid:

the finding is valid because the creation of DisputeGame is done via [create function](https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/DisputeGameFactory.sol#L84-L122) and then stores the new created DisputeGame in [_disputeGameList.push(id);](https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/DisputeGameFactory.sol#L120) array and Since the Default Status of gameProxy is IN_PROGRESS the Withdrawal transaction can be proven on In-Progress Game Status. as it is described in the issue.

check this issue https://github.com/sherlock-audit/2024-02-optimism-2024-judging/issues/241

**Comment by 0xlastByte** [comment]
> @smartcontracts please verify this issue whether it's valid or not 😢

bro create Escalate copy my Escalate because this issue is valid.

**Comment by shanb1605** [comment]
@0xlastByte LOL 😆  I guess the escalation period has ended

**Comment by 0xlastByte** [comment]
i think the finding is valid as i explained

**Comment by nevillehuang** [comment]
I believe this issue is invalid. Although withdrawals can be proven while game is in progress, it can only be finalized when `DEFENDER_WINS` as seen [here](https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/L1/OptimismPortal2.sol#L493)

**Comment by shanb1605** [comment]
As I go through the Fault proof walkthrough this is the flow I understand
```
challenge game -> resolve -> prove -> finalize
```
So, OP_Portal2 code says that Invalid game statuses like `Challenger Wins` are not proven. My issue point is that `IN_PROGRESS` is also an `invalid` game status. So there should be a check to prevent IN_Progress from being proven.

@nevillehuang your point clearly tells us that it can be taken care at `finalzewithdrawl()` function. This clearly shows that `proveWithdrawlTransaction` is less taken care and no interest in fixing this. All could take simple fix in require condition.

If `IN_Progress` game status can be left to prove is Intentional, I don't want to argue further because somewhat it shows a clear intention of making this report Invalid.

P.S: I will chain this medium bug and hope I will find critical bug from this when Fault Proof is on the Immuenfi OP BB program.

**Comment by t-maker564** [comment]
> I believe this issue is invalid. Although withdrawals can be proven while game is in progress, it can only be finalized when `DEFENDER_WINS` as seen [here](https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/L1/OptimismPortal2.sol#L493)

bro look at the bug https://github.com/sherlock-audit/2024-02-optimism-2024-judging/issues/241 to understand the when IN_PROGRESS is stored in 
```solidity
provenWithdrawals[withdrawalHash][msg.sender] = ProvenWithdrawal({ 
    disputeGameProxy: gameProxy, // <- IN_PROGRESS stored as status
    timestamp: uint64(block.timestamp)
});
``` 
so the next time user wants to re-prove the game Dispute when it is resolved to DEFENDER_WINS the user cannot prove the withdrawal because it will revert here 

```solidity 
// it will revert because status is IN_PROGRESS not CHALLENGER_WINS
IDisputeGame oldGame = provenWithdrawal.disputeGameProxy;
require(
    provenWithdrawal.timestamp == 0 || 
    oldGame.status() == GameStatus.CHALLENGER_WINS ||
    disputeGameBlacklist[oldGame] || 
    oldGame.gameType().raw() != respectedGameType.raw(),
    "OptimismPortal: withdrawal hash has already been proven, and the old dispute game is not invalid"
);
```

**Comment by 0xlastByte** [comment]
@nevillehuang @smartcontracts 

> I believe this issue is invalid. Although withdrawals can be proven while game is in progress, it can only be finalized when `DEFENDER_WINS` as seen [here](https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/L1/OptimismPortal2.sol#L493)

and thats what we are talking about the withdrawal won't be proven while it should be proven but because of this described issue in https://github.com/sherlock-audit/2024-02-optimism-2024-judging/issues/241, the user will not be able to prove a valid withdrawal.

bro look at the bug https://github.com/sherlock-audit/2024-02-optimism-2024-judging/issues/241 to understand. 
IN_PROGRESS is stored in because its the default status:
```solidity
provenWithdrawals[withdrawalHash][msg.sender] = ProvenWithdrawal({ 
    disputeGameProxy: gameProxy, // <- IN_PROGRESS stored as status
    timestamp: uint64(block.timestamp)
});
``` 
so the next time user wants to re-prove the game Dispute when it is resolved to DEFENDER_WINS the user cannot prove the withdrawal because it will revert here 

```solidity 
// it will revert because status is IN_PROGRESS not CHALLENGER_WINS
IDisputeGame oldGame = provenWithdrawal.disputeGameProxy;
require(
    provenWithdrawal.timestamp == 0 || 
    oldGame.status() == GameStatus.CHALLENGER_WINS ||
    disputeGameBlacklist[oldGame] || 
    oldGame.gameType().raw() != respectedGameType.raw(),
    "OptimismPortal: withdrawal hash has already been proven, and the old dispute game is not invalid"
);
```
