### ISSUE TITLE
ctf_sec - Resolve game can running out of gas if subgame array is too large

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-optimism-2024-judging#25]
ctf_sec

medium

# Resolve game can running out of gas if subgame array is too large

## Summary

Resolve game can running out of gas

## Vulnerability Detail

WHEN resolve the claim, the code iterate all the items in sub game array

```solidity
uint256[] storage challengeIndices = subgames[_claimIndex];
uint256 challengeIndicesLen = challengeIndices.length;
```

then we call:

```solidity
for (uint256 i = 0; i < challengeIndicesLen; ++i) {
    uint256 challengeIndex = challengeIndices[i];

    // INVARIANT: Cannot resolve a subgame containing an unresolved claim
    if (subgames[challengeIndex].length != 0) revert OutOfOrderResolution();

    ClaimData storage claim = claimData[challengeIndex];

    // If the child subgame is uncountered and further left than the current left-most counter,
    // update the parent subgame's `countered` address and the current `leftmostCounter`.
    // The left-most correct counter is preferred in bond payouts in order to discourage attackers
    // from countering invalid subgame roots via an invalid defense position. As such positions
    // cannot be correctly countered.
    // Note that correctly positioned defense, but invalid claimes can still be successfully countered.
    if (claim.counteredBy == address(0) && leftmostCounter.raw() > claim.position.raw()) {
        countered = claim.claimant;
        leftmostCounter = claim.position;
    }
}
```

The problem is that when making a move, the data is pushed into the sub games array:

```solidity
// Update the subgame rooted at the parent claim.
subgames[_challengeIndex].push(claimData.length - 1);
```

If there are too many moves against a subgame challange index,

when resolve the claim, the for loop can running out of gas

make it expensive / impossible to resolve the game state and distribute the bond

## Impact

Resolve claim can cause too much gas when iterating over the subgame challanges

## Code Snippet

https://github.com/sherlock-audit/2024-02-optimism-2024/blob/f216b0d3ad08c1a0ead557ea74691aaefd5fd489/optimism/packages/contracts-bedrock/src/dispute/FaultDisputeGame.sol#L442

https://github.com/sherlock-audit/2024-02-optimism-2024/blob/f216b0d3ad08c1a0ead557ea74691aaefd5fd489/optimism/packages/contracts-bedrock/src/dispute/FaultDisputeGame.sol#L311

## Tool used

Manual Review

## Recommendation

Consider iterate over the subgame in batch if the subgame array length given a index is too large.

**Comment by JeffCX** [comment]
Escalate

this should be duplicate of #7 

usually it does not matter because issue 7 is not consider valid,

But based on issue 7's sponsor comments:

https://github.com/sherlock-audit/2024-02-optimism-2024-judging/issues/7#issuecomment-2059619691

> we would like to reward this report outside of this contest. We are currently coordinating to determine reward amounts and which platform will be used to distribute the reward.

the duplicate may matter, so I still want to escalate to make sure the issue has correct duplicate status.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> this should be duplicate of #7 
> 
> usually it does not matter because issue 7 is not consider valid,
> 
> But based on issue 7's sponsor comments:
> 
> https://github.com/sherlock-audit/2024-02-optimism-2024-judging/issues/7#issuecomment-2059619691
> 
> > we would like to reward this report outside of this contest. We are currently coordinating to determine reward amounts and which platform will be used to distribute the reward.
> 
> the duplicate may matter, so I still want to escalate to make sure the issue has correct duplicate status.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
By sherlock's rules, this issue is clearly invalid because it doesn't provide a numerical/coded PoC to support a gas consumption revert finding as noted [here](https://docs.sherlock.xyz/audits/judging/judging#vi.-requirements). So I believe  the escalation should be rejected, but I will leave it to sponsor to decide whether they want to award the finding or not.

**Comment by JeffCX** [comment]
> By sherlock's rules,

Thanks for reviewing my escalation

https://docs.sherlock.xyz/audits/judging/judging#vi.-requirements

I wonder if you are referring to 

> PoC is required for all issues falling into any of the following groups:

> attacks related to the gas consumption and/or reverting message calls

emm yeah while the POC is not numerical or coded (docs does not say it has to be numerical or coded),

this is the POC in original submission.

<img width="814" alt="Screenshot 2024-04-29 at 7 10 23 AM" src="https://github.com/sherlock-audit/2024-02-optimism-2024-judging/assets/25846666/317cdded-2f6e-48ae-aa2f-f7f1facaa37d">

this is the core exploits because the sub game challenge array size only keep expanding,

whether the exact number of game is 3000, or 10000, I think the statement above should be able to qualify as duplicates

**Comment by nevillehuang** [comment]
@JeffCX Yes I am referring to that, but like you mentioned, it is a statement with insufficient proof for that statement. 

- It says the loop can run of out gas --> but how exactly? The gas consumptions rates should be explicitly stated based on opcode gas requirements.
- It says make it expensive/impossible to resolve the game state and distribute the bond --> but how exactly? Should have possibly shown how the block gas limit could reached?

I don't deny it is a duplicate, but I don't think it affects the escalation outcome here. I will highlight to sponsor to see if they are keen to reward the issue.

**Comment by Evert0x** [comment]
> PoC is required for all issues falling into any of the following groups:

For that reason I plan to reject the escalation

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [JEFFCX](https://github.com/sherlock-audit/2024-02-optimism-2024-judging/issues/25/#issuecomment-2073811368): rejected

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/ethereum-optimism/optimism/pull/10248
