### ISSUE TITLE
bin2chen - claimCredit() user may not be able to claim bond

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-optimism-2024-judging#43]
bin2chen

medium

# claimCredit() user may not be able to claim bond

## Summary
`FaultDisputeGame` is created through `ClonesWithImmutableArgs`. 
Under the mechanism of `ClonesWithImmutableArgs`, every method execution automatically appends `ImmutableArgs` to the `calldata`. 
As a result, the `calldata` is never empty. 
So, if the first parameter of `ImmutableArgs`, namely `rootClaim`, happens to match the first 4 bytes of another contract's method signature
 it can lead to unexpected behavior. 
Example, when executing `address(FaultDisputeGame).transfer()`, instead of invoking the expected `fallback()` function, it may inadvertently trigger another method, causing the `transfer()` operation to fail. 
Currently, this issue affects the `FaultDisputeGame.claimCredit()` method, preventing users from retrieving their bond.
`claimCredit()` -> `DelayedWETH.withdraw()` -> `WETH98.withdraw()` -> `payable(msg.sender).transfer(wad);`.

## Vulnerability Detail
When `FaultDisputeGame` is cloned, it specifies `ImmutableArgs = abi.encodePacked(_rootClaim, parentHash, _extraData)`. Under the mechanism of `ClonesWithImmutableArgs`, every method execution automatically appends this `ImmutableArgs`. 
Due to this automatic appending, consider the scenario where we execute `address(FaultDisputeGame).transfer()`. 
The actual `calldata` would be: `["" + 0x20 root claim + 0x20 parentHash + 0x20 extraData + 0x02 CWIA bytes]`. 
Consequently, the `first 4 bytes` of `rootClaim` might be mistakenly interpreted as a method selector. 
If it coincidentally matches an existing contract's method signature, it could lead to unintended behavior, resulting in a revert due to `OUT GAS` or  `payable error`  or an `abi error`
```solidity
gameType() = 0xbbdc02db
resolve(..) = 0x2810e1d6
resolveClaim(..)=0xfdffbb28
...
...
...
other function
```

The current execution steps of `FaultDisputeGame.claimCredit()` are as follows:
`claimCredit()`->`DelayedWETH.withdraw()`->`WETH98.withdraw()`->`payable(msg.sender).transfer(wad);`
```solidity
contract WETH98 is IWETH {
...
    function withdraw(uint256 wad) public virtual {
        require(balanceOf[msg.sender] >= wad);
        balanceOf[msg.sender] -= wad;
@>      payable(msg.sender).transfer(wad);   // will revert if have Special rootClaim
        emit Withdrawal(msg.sender, wad);
    }
```

## POC
The following code demonstrates that the  `first 4 bytes`  of `rootClaim` is  `gameType()`.
`transfer()` will execute the `function gameType () `

```solidity
contract CounterTest is Test {
  using ClonesWithImmutableArgs for address;
  receive() external payable { }
  fallback() external payable { }
  function gameType() external{
  }
  function test() external {
    bytes memory b = abi.encodeWithSignature("gameType()","xxx","xxx");
    bytes32 rootClaim;
    assembly {
      rootClaim :=mload(add(b,0x20)) //bytes to bytes32
    }
    CounterTest clone = CounterTest(address(this).clone(abi.encodePacked(rootClaim,blockhash(block.number - 1),uint256(123))));
    vm.deal(address(this), 1 ether);
    payable(clone).transfer(10);
  }
}
```

```console
$ forge test -vvv

Traces:
  [73684] CounterTest::test()
    ├─ [30246] → new <unknown>@0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f
    │   └─ ← 151 bytes of code
    ├─ [0] VM::deal(CounterTest: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496], 1000000000000000000 [1e18])
    │   └─ ← ()
    ├─ [338] 0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f::fallback{value: 10}()
    │   ├─ [145] CounterTest::gameType() [delegatecall]
    │   │   └─ ← EvmError: Revert
    │   └─ ← EvmError: Revert
    └─ ← EvmError: Revert
```

## Impact

The number of `rootClaim`  and the number of `FaultDisputeGame` public function are still relatively large, and there is still a certain chance that there will be a special `first 4 bytes`
This will cause the user's bond to be locked

Another possible malicious user can also maliciously specify a special `rootClaim`, causing other challengers to lose the submitted `bond`, but the user agrees to lose `eth`
## Code Snippet
https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/FaultDisputeGame.sol#L641
## Tool used

Manual Review

## Recommendation

Modify `withdraw (address _guy, uint256 _wad)` do not transfer to `game` and then to `gun`, but directly to `guy`
```diff
    function claimCredit(address _recipient) external {
...
        WETH.withdraw(_recipient, recipientCredit);

-       // Transfer the credit to the recipient.
-       (bool success,) = _recipient.call{ value: recipientCredit }(hex"");
-       if (!success) revert BondTransferFailed();
    }

contract DelayedWETH is OwnableUpgradeable, WETH98, IDelayedWETH, ISemver {
...

    function withdraw(address _guy, uint256 _wad) public {
        require(!config.paused(), "DelayedWETH: contract is paused");
        WithdrawalRequest storage wd = withdrawals[msg.sender][_guy];
        require(wd.amount >= _wad, "DelayedWETH: insufficient unlocked withdrawal");
        require(wd.timestamp > 0, "DelayedWETH: withdrawal not unlocked");
        require(wd.timestamp + DELAY_SECONDS <= block.timestamp, "DelayedWETH: withdrawal delay not met");
        wd.amount -= _wad;
-       super.withdraw(_wad);
+       require(balanceOf[msg.sender] >= wad);
+       balanceOf[msg.sender] -= wad;
+       payable(_guy).transfer(wad);
+       emit Withdrawal(msg.sender, wad);
    }
```

**Comment by 0xdeadbeef0x** [comment]
Escalate

This is a very clever issue! 

However I argue that no funds are at risk and this show be low/invalid:
1. Extremely low (but exists) likelihood
2. Funds can be recovered by admin using safeguard function `DelayedWETH.hold()` and `DelayedWETH.recover()`   - see https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid item "8". 
```
Funds are temporarily stuck and can be recovered by the administrator or owner
```

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is a very clever issue! 
> 
> However I argue that no funds are at risk and this show be low/invalid:
> 1. Extremely low (but exists) likelihood
> 2. Funds can be recovered by admin using safeguard function `DelayedWETH.hold()` and `DelayedWETH.recover()`   - see https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid item "8". 
> ```
> Funds are temporarily stuck and can be recovered by the administrator or owner
> ```
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by MightyFox3** [comment]
Admin may call [DelayedWETH.hold](https://github.com/sherlock-audit/2024-02-optimism-2024/blob/f216b0d3ad08c1a0ead557ea74691aaefd5fd489/optimism/packages/contracts-bedrock/src/dispute/weth/DelayedWETH.sol#L92) to grant owner allowance, then owner can transfer the locked fund and the owner is trusted, so shall we mark severity as low or informational?

**Comment by trust1995** [comment]
With the scoping logic declared by Optimism / Sherlock team, since there is clearly no airgap bypass and funds are safe under the security architecture assumptions, this would need to be treated as Low / Informational.

**Comment by bin2chen66** [comment]
https://docs.google.com/document/d/1xjvPwAzD2Zxtx8-P6UE69TuoBwtZPbpwf5zBHAvBJBw/edit
After re-reading this document again, I rather agree with 0xnevi's initial judgment
The cause of the problem has nothing to do with the game mechanics, neither the winner nor the loser participant can retrieve the bond.（As long as the contract requires eth to be affected by this issue）
I would like to keep the original judgment. Unless the Audit Judgment Rules document has changed
thanks

**Comment by shealtielanz** [comment]
This finding is a real edge case and it is outside the game resolution logic if not found now the case would have been extremely difficult to tackle when deployed

**Comment by nevillehuang** [comment]
Agree with @bin2chen66, based on the agreed upon scope details and the line drawn, I believe this is still valid based on comments [here](https://github.com/sherlock-audit/2024-02-optimism-2024-judging/issues/43#issuecomment-2070262864). 

> Issues with a root cause in the non-game contracts are IN SCOPE

- Root Cause: Unsuspected creation of FDG with rootclaim [here](https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/DisputeGameFactory.sol#L106 )corresponding to another contracts function selector
- Impact: Can potentially block withdrawals, although no safety mechanism bypassed, given DelayedWeth can be used to recover bonds.

**Comment by zobront** [comment]
Hey @nevillehuang — I want to add one perspective here. I'm a huge fan of this issue and private messaged @bin2chen66 to give him props. I think it was the coolest find in the whole contest.

I also agree with you about the scope. It's borderline, but I can see the logic that the root cause is in a non-game contract, so even though it would be caught by the DelayedWETH mechanism, it should be in scope.

However, I want to examine the severity of the finding.

There are `256**4 ~= 4.3 billion` possible combinations for the first 4 bytes of the root claim. There is only 1 of those that collides with the `resolveClaim()` function. So the odds of this happening are 1 in 4.3 billion. Assuming we add a root during each L1 block (unlikely), this still won't occur on average for 1600 years.

In terms of severity, the vast majority of games will not have any disputes, so it is highly likely that when this happens in 1600 years, there will be no impact. Since there is no benefit to the attacker, there's no reason to think this situation is more likely to have a dispute than others. In the exteremely rare case that it would, the worst case is simply a loss of bond (while the game resolves correctly).

As much as I love this finding (and ignoring the question as to whether it is in scope), given these two facts, I don't see how there is any argument that this could be a Medium severity. Unfortunately, I think it must be downgraded to Low.

**Comment by nevillehuang** [comment]
@zobront @bin2chen66, Thanks for the analysis. Given creation of games is permisionless, would we be able to maliciously craft the root claim to lock challengers of their bonds?

**Comment by zobront** [comment]
@nevillehuang This would require us putting up an equal amount of bonds that we would also not be able to get back. I don't think it's possible to see that as an "attack" that someone would do intentionally.

I believe there have been past Sherlock judgments about this ("Is wasting your own money to waste an approximately equal amount of an innocent party's money considered valid?") and it was ruled invalid, but I'm not positive, so should check with Sherlock team to confirm.

**Comment by bin2chen66** [comment]
hey @zobront 
>There are 256**4 ~= 4.3 billion possible combinations for the first 4 bytes of the root claim. There is only 1 of those that collides with the resolveClaim() function.

I need to correct one thing, this is not only collision with "resolveClaim()", it should be collision with all the method signatures in this contract, about ~30+

And I'm not sure if this is how the probability of occurrence is calculated. Don't know much about it.

**Comment by zobront** [comment]
For the probability of occurrence, based on Expectation of the Geometric Distribution, we can expect the number of trials until something happens is `E(X) = 1/p` where `p` is the probability. So in this case it's `1/1/4.3b = 4.3b`.

But agreed on the other collisions, so it should occur in ~150 million tries instead. I don't think this changes the assessment at all (especially given that in most cases there will be no challenge and therefore cost will just be the initial bond) but it's an important clarification.

**Comment by guhu95** [comment]
@nevillehuang as pointed out above, since the admin can `recover` or `hold` to rescue the funds if this happens, there isn't enough impact according to the [validity rules](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid) (number 8 on the list):

> Funds are temporarily stuck and can be recovered by the administrator or owner.

(I too am a fan of this very clever finding, however I think it's both low likelihood and low impact, and so low severity)

**Comment by shealtielanz** [comment]
Requirements for medium are stated:
> Causes a loss of funds but requires certain external conditions or specific states, or a loss is highly constrained. The losses must exceed small, finite amount of funds, and any amount relevant based on the precision or significance of the loss.
Breaks core contract functionality, rendering the contract useless or leading to loss of funds.


This issue perfectly fits the in scope vuls of this contest while also fitting into the Sherlock requirements for medium. 
This collision is very possible and it's not possible to know when it can happen.
I agree with bin2chen and nevi.
This is a valid medium.

**Comment by guhu95** [comment]
> Requirements for medium are stated:
> 
> > Causes a loss of funds ..

@shealtielanz unless I'm missing something, there is no loss of funds. The funds are temporarily locked due to the transfer failing. They would be lost if transferred to someone else's control, but the admin is able to rescue them if this happens.

**Comment by shealtielanz** [comment]
The Impact of this issue isn't just boiled down to one issue as other issues can arise due to this, the transfer() scenario is just a given instance(please refer to the Impact section of the original report), where it can equally break other core functionalities of the contract and also can lead to loss of funds.

**Comment by bin2chen66** [comment]
> For the probability of occurrence, based on Expectation of the Geometric Distribution, we can expect the number of trials until something happens is `E(X) = 1/p` where `p` is the probability. So in this case it's `1/1/4.3b = 4.3b`.
> 
> But agreed on the other collisions, so it should occur in ~150 million tries instead. I don't think this changes the assessment at all (especially given that in most cases there will be no challenge and therefore cost will just be the initial bond) but it's an important clarification.

If based on this algorithm, am I to understand it like this?
In 1600 years / (30+ method) = ~ 50 years
That is, it will happen once in 50 years.
But we don't know when it will happen?
So is it possible to calculate a rough estimate of the probability
Probability of occurrence in 50 years     100%
Probability of occurrence in 25 years     50%
Probability of occurrence in 10 years      20%
Probability of occurrence in 1 year          2%

Not quite sure how sherlock defines this effective probability

**Comment by bemic** [comment]
> Probability of occurrence in 50 years 100%
> Probability of occurrence in 25 years 50%
> Probability of occurrence in 10 years 20%
> Probability of occurrence in 1 year 2%

This is true if we use all blocks to find a match (~7000 blocks per day). While I like the idea of this issue, I think the real possibility is very very small.

**Comment by Haxatron** [comment]
I think this issue can be considered Medium IF there were no restrictions in scope during the contest. 

But since the intended purpose of this contest was to ensure that the safeguards work properly and this issue is recoverable by the DelayedWETH safeguard, I believe the sponsor is correct in saying that it should not be included in the main pot in https://github.com/sherlock-audit/2024-02-optimism-2024-judging/issues/43#issuecomment-2059621795

This definitely should be rewarded from the side pot though.

**Comment by zobront** [comment]
Nonono @bemic please don't respond to his factual ask if you don't understand probability. It makes it difficult for the judge to parse the issue.

@bin2chen66 That is unfortunately not how it works. At 54 years, it doesn't go up to a 100% chance of happening. Here's what we can say, to summarize the facts of the likelihood for the judge:
- Each block proposed, there is a 1 in 143mm chance that this happens (4.3bn / 30)
- To calculate the odds of it happening sooner, we can use `1 - ((143mm-1)/143mm)^tries`. 
- For example, for odds of it happening within 10 years, we have `1 - ((143mm-1)/143mm)^(10*365*24*60*5) ~= 17%`. 
- For example, the odds of it happening within 20 years, we have `1 - ((143mm-1)/143mm)^(20*365*24*60*5) ~= 30%`. 
- For example, the odds of it happening within 50 years, we have `1 - ((143mm-1)/143mm)^(20*365*24*60*5) ~= 61%`. 

Note that these are the odds of the collision happening (if there is a proposal every single block). The odds of there being a dispute so that significant bonds are locked up is much much much lower.

Edit: Originally typed this while holding a baby and got the math wrong lol, fixed now.

**Comment by Evert0x** [comment]
Based on the conversation, I understand that
a) The issue is in the scope of the contest
b) The issue is extremely unlikely to happen, but could happen at any time
c) If the issue occurs, the bond of a single user is locked up
d) Funds can be recovered by admin using safeguard functions DelayedWETH.hold() and DelayedWETH.recover()

> User experience and design improvement issues: Issues that cause minor inconvenience to users where there is no material loss of funds are not considered valid. Funds are temporarily stuck and can be recovered by the administrator or owner. Also, if a submission is a design opinion/suggestion without any clear indications of loss of funds is not a valid issue.

I don't think this rule applies. The report clearly talks about a bug, not about a suggestion for the protocol team to improve their design.  

I believe the following Medium severity definition applies. That's why I plan to reject the escalation en keep it Medium severity, this depends on a), b), and c). 

> Causes a loss of funds but requires certain external conditions or specific states, or a loss is highly constrained. The losses must exceed small, finite amount of funds, and any amount relevant based on the precision or significance of the loss.

**Comment by trust1995** [comment]
>> User experience and design improvement issues: Issues that cause minor inconvenience to users where there is no material loss of funds are not considered valid. Funds are temporarily stuck and can be recovered by the administrator or owner. Also, if a submission is a design opinion/suggestion without any clear indications of loss of funds is not a valid issue.

> I don't think this rule applies. The report clearly talks about a bug, not about a suggestion for the protocol team to improve their design.

It does apply, because the first part (before `Also...`) is fully fulfilled. In practice as per zobront's calculations, this would happen once every many hundreds/thousands of years (there's no proposal every block), and in that event the worst case is an inconvenience forcing Optimism to make use of its readily prepared safety methods.

The bug root cause is brilliant, but as is often the case the end impact is not as brilliant as the bug itself. We must be wary of brilliance bias when assessing submissions.



> Causes a loss of funds but requires certain external conditions or specific states, or a loss is highly constrained. The losses must exceed small, finite amount of funds, and any amount relevant based on the precision or significance of the loss.

Factually incorrect, it does NOT lead to loss of funds under the assumption of a responsible guardian as explicitly stated in the contest docs and enforced in other submissions.

**Comment by guhu95** [comment]
@Evert0x in what possible circumstances can funds be lost due to this bug? Are you assuming the admin is revoked, or that the `hold()` / `recover()` are not present?

**Comment by MiloTruck** [comment]
I didn't want to participate in the escalation wars, but the resolution is so unconvincing I couldn't help myself.

> b) The issue is extremely unlikely to happen, but could happen at any time

This feels like an over-generalization of the problem. Someone finding the private key to the zero address is also "extremely unlikely to happen, but could happen at any time". Does that make Ethereum a bug? The question here is whether the probability of this issue occurring is sufficiently low such that it is considered safe.

Given that findings regarding using `uint32` for `block.timestamp` has historically been judged as invalid since year 2106 is far enough into the future, we'll use 82 years as the point of reference.

From [the current `L2OutputOracle` contract](https://etherscan.io/address/0xdfe97868233d1aa22e815a266982f2cf17685a27), we can see that [a proposal is submitted roughly every hour](https://docs.google.com/spreadsheets/d/1zZoVcwS1B1Dcfv8oUqX1vLDT_S-yuTXWl9_ZbjxuUYQ).

Following Zach's calculations, the probability of a collision occurring in 82 years is:

```
1 - (1 - 1/143mm) ^ (82 * 365 * 24) ~= 0.0050048
```

This means there's a 0.5% chance of this issue occurring before the year 2106.

> I believe the following Medium severity definition applies. That's why I plan to reject the escalation en keep it Medium severity, this depends on a), b), and c).
>
> > Causes a loss of funds but requires certain external conditions or specific states, or a loss is highly constrained. The losses must exceed small, finite amount of funds, and any amount relevant based on the precision or significance of the loss.

As Trust and guhu have both pointed out, there isn't any loss of funds here as they can be recovered by the admin. The whole premise of this contest was that the safeguards _are_ working and _will_ be used when needed. As such, the only impact here is that funds are temporarily stuck until they are recovered.

Given the absolute rock-bottom likelihood and non-severe impact, I don't see how this is even remotely close to medium severity.

**Comment by 54710adk341** [comment]
Arguing probability does not hold any weight here, a high probability would justify a High, a low probability would justify a Medium. This is a valid Medium.

**Comment by alexfilippov314** [comment]
> Arguing probability does not hold any weight here, a high probability would justify a High, a low probability would justify a Medium. This is a valid Medium.

I'm afraid it is not how it works. There is always a tiny probability of finding the owner's private key, and the impact in this case is as high as it can be. Does this imply that owner's key brute-forcing is always a valid Medium issue?

**Comment by shealtielanz** [comment]
Your example uses false equivalence, this report has no similarities with what you just stated

**Comment by alexfilippov314** [comment]
My only point is that you can't just ignore probability. The current system with low/medium/high likelihood/impact is just an approximation of a more general risk formula: Risk = Likelihood x Impact. And you can't just say that if it can happen, then the likelihood is low. At some point, likelihood becomes negligible. MiloTruck provided some valuable reasoning where he is trying to estimate this point. And the counterargument was: probabilities don't matter. Well, my example clearly demonstrates that they do.

**Comment by 54710adk341** [comment]
It holds no weight in this case because a low probability would still net a Medium using Sherlock rules, if you don't agree with the Sherlock rules I would suggest to open SJIP:
- https://github.com/sherlock-protocol/governance-and-discussion/discussions/4

**Comment by Evert0x** [comment]
Thanks for the discussion. It's clear to me that this issue should be invalidated.

The following statement is true. 

> It does apply, because the first part (before Also...) is fully fulfilled. In practice as per zobront's calculations, this would happen once every many hundreds/thousands of years (there's no proposal every block), and in that event the worst case is an inconvenience forcing Optimism to make use of its readily prepared safety methods.

Besides that. There is no loss of funds due to "d) Funds can be recovered by admin using safeguard functions DelayedWETH.hold() and DelayedWETH.recover()"

And finally, I agree that probabilities matter. Although not clearly stated in the judging guidelines, it's common sense to use for risk ratings.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xdeadbeef0x](https://github.com/sherlock-audit/2024-02-optimism-2024-judging/issues/43/#issuecomment-2074347950): accepted
