### ISSUE TITLE
obront - Blacklisted games still update Anchor State Registry, bricking game type

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-optimism-2024-judging#81]
obront

medium

# Blacklisted games still update Anchor State Registry, bricking game type

## Summary

When an invalid game is resolved, the `AnchorStateRegistry` is immediately updated to reflect the new state. This update does not have any delay for the protocol team to fix things if it's incorrect, and there is no way to override the updated state once it's discovered.

## Vulnerability Detail

When a game is resolved, three things happen, all of which should account for the possibility of a fraudulent game:

✅ The status is set based on who wins. If a game incorrectly resolves to `DEFENDER_WINS`, the guardian has time to blacklist the game before any withdrawals can be finalized against it.

✅ Bonds are paid out. If a game incorrectly resolves, the `DelayedWETH` owner has time to take the funds before any bonds can be withdrawn.

❌ The `AnchorStateRegistry` is updated. If a game is resolved incorrectly, the `AnchorStateRegistry` is immediately updated to reflect the new state. This is an irreversible operation that permanently updates the last trusted state to the `rootClaim` of the game.

In the event that the game type is still being used (ie if the exploited game was blacklisted instead of the whole game type being abandoned), this leads to an `AnchorStateRegistry` that requires all games of this type to build off the incorrect state.

## Impact

In the best case, this will lead to valid claims not being able to be proven, and the game type needing to be changed to manually reset the system.

In the worst case, it could open up the door to an attacker skirting the off-chain monitoring by performing a valid state transition from an invalid starting point.

## Code Snippet

https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/FaultDisputeGame.sol#L386-L402

https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/AnchorStateRegistry.sol#L59-L87

## Tool used

Manual Review

## Recommendation

`tryUpdateAnchorState()` should act similarly to the other impacts of a resolved game, implementing some time delay before trusting the result.

For example, the `AnchorStateRegistry` could store an array of state updates along with the timestamp they were submitted. Once a period of time has passed, anyone can permissionlessly integrate these updates into the `anchors` array.

**Comment by JeffCX** [comment]
Escalate. I think the issue is clearly a medium issue if the severity is not high,

as for sponsor comments:

> Blacklisting is meant as a temporary option to prevent a game from being used to execute withdrawals

but prevent a game from being used to execute withdrawals means a game must be resolved in a invalid output root.

then if we already know the output root is invalid, there is no reason for other game to be created using that invalid out root because that means user may lose their bond that are used to create the game which leads to massive loss of fund.

while guardian has the ability to switch game types in response to invalid game resolutions using airgap,

the game that used the blocklisted game (that produce a invalid output root) may lose their bond.

**Comment by sherlock-admin2** [comment]
> Escalate. I think the issue is clearly a medium issue if the severity is not high,
> 
> as for sponsor comments:
> 
> > Blacklisting is meant as a temporary option to prevent a game from being used to execute withdrawals
> 
> but prevent a game from being used to execute withdrawals means a game must be resolved in a invalid output root.
> 
> then if we already know the output root is invalid, there is no reason for other game to be created using that invalid out root because that means user may lose their bond that are used to create the game which leads to massive loss of fund.
> 
> while guardian has the ability to switch game types in response to invalid game resolutions using airgap,
> 
> the game that used the blocklisted game (that produce a invalid output root) may lose their bond.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
Based on the agreed upon scope details and the line drawn, I believe this is still invalid based on comments [here](https://github.com/sherlock-audit/2024-02-optimism-2024-judging/issues/144#issuecomment-2062283773). 

> Issues with a root cause in the game that ARE handled by the safeguards are OUT OF SCOPE (note that this includes subgame resolution issues and theft of bonds, as both of these issues stem from the game that was assumed to be insecure, so are only valid if they are able to escape the safeguards).

- Root cause: `resolve()` logic in FDG game contract immediately updates anchor state registry even when games resolve incorrectly (eventually blacklisted) as seen [here](https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/FaultDisputeGame.sol#L401)
- Impact: If admin do not switch game types during airgap, future valid claims cannot be resolved due to incorrect state. Airgap is not bypassed, since game type will have to be updated.

**Comment by Evert0x** [comment]
Planning to reject escalation and keep issue as is

**Comment by Evert0x** [comment]
Result:
Invalid
Has Duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [JEFFCX](https://github.com/sherlock-audit/2024-02-optimism-2024-judging/issues/81/#issuecomment-2073919863): rejected
