### ISSUE TITLE
obront - Data overwrite bug in ClonesWithImmutableArgs could be abused to deploy invalid proxy

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-optimism-2024-judging#83]
obront

medium

# Data overwrite bug in ClonesWithImmutableArgs could be abused to deploy invalid proxy

## Summary

The `ClonesWithImmutableArgs` library can be manipulated when data with an arbitrary length is passed to the `clone` function. This manipulation can lead to proxies with undefined behavior, which could risk the safety of the dispute game system.

## Vulnerability Detail

The basic idea of `ClonesWithImmutableArgs` is to deploy a proxy contract with a set of immutable arguments included in the code. When the proxy is called, it delegate calls to the implementation, and includes the immutable arguments in the call data. These values can be accessed by indexing into the calldata at the correct offsets.

In order to create this code, the `clone()` function stores the `extraLength` in multiple places in the code. This is the length of the arguments that the proxy is supposed to store.

In order to perform these additions, the hardcoded proxy code has gaps (`0000`) in the code. This is then `or`d with `runSize` (which is equal to `extraLength - 53`) and `extraLength` at the right offset to add the length into these gaps.

```solidity
mstore(
    ptr,
    or(
        hex"610000_3d_81_600a_3d_39_f3_36_3d_3d_37_3d_3d_3d_3d_610000_80_6035_36_39_36_01_3d_73",
        or(
            shl(0xe8, runSize),
            shl(0x58, extraLength)
        )
    )
)
```
However, there is no check that these values will in fact fit in the 2 bytes that are allocated to them. The result is that, if a longer length is passed, the data will overwrite the code to the left of the `extraLength` value with its extra digits.

This is important because by `or`ing additional bits with the preceding opcode, `0x61` (PUSH2) can be changed into any higher op code. For example, if it is changed into PUSH4, it will consume the following bytes (`3d81`) as the data to push, rather than performing the operations.

This gives an attacker a lot of power to determine the behavior of the proxy, skipping intended operations (like above) or jumping into data that is not intended to be executed (like the other PUSH values) in order to create undefined behavior.

## Proof of Concept

As a simple proof of concept, we can see above that if we turn `PUSH2` into `PUSH18`, it will skip all the way to the later `00` values. These values represent the `STOP` op code, and will leave to a contract being deployed with no bytecode.

```solidity
function testBreakClones() public {
    // If the initial PUSH2 becomes PUSH18, it eats next 18 bytes & leaves us with 00 for STOP (returning empty bytecode).
    // To turn PUSH2 into PUSH18, we need to add a value to the 16 slot (1 << 4).
    // Assuming we want 0s for the 2 bytes (16), then we need length == 1 << (16 + 4) == 1048576
    // The value entered into the slot is `length + 63 - 10`, so `targetLength = 1048576 - 53 = 1048523`
    // `cast 2h 1048523` = 0xfffcb
    bytes memory b = new bytes(0xfffcb);
    address proxy = ClonesWithImmutableArgs.clone(address(123), abi.encodePacked(uint(1), bytes32(0), b));

    // A proxy address is returned, but it has no code.
    assert(address(proxy) != address(0));
    assert(address(proxy).code.length == 0);
}
```
This is a simple example, but it shows the potential for abuse.

[Note that this isn't a risk in the current game due to the check that `extraData.length < 32`. However, since our focus is on the surrounding system and ensuring it is robust against incorrect games, this vulnerablity is important to address.]

## Impact

The `DisputeGameFactory` can deploy proxies with undefined behavior, breaking the assumptions of the other interacting contracts and potentially leading to risky behavior.

## Code Snippet

https://github.com/Saw-mon-and-Natalie/clones-with-immutable-args/blob/105efee1b9127ed7f6fedf139e1fc796ce8791f2/src/ClonesWithImmutableArgs.sol#L94-L103

## Tool used

Manual Review

## Recommendation

Use Solady's `LibClone`, which has addressed this issue thanks to the incredible find in their [Cantina audit](https://github.com/Vectorized/solady/blob/main/audits/cantina-solady-report.pdf) and is safe from this attack.

**Comment by guhu95** [comment]
Not related to the contest. Just wanted to inform anyone reading through these, or generally interested in this bug (@zobront, @smartcontracts), to prevent this false positive from further propagating. This is an interesting case where EIP > POC.

Both this finding, and the original Cantina finding seem invalid (at the EVM level) due to ignoring code size limits of [EIP-3860 and EIP-170](https://eips.ethereum.org/EIPS/eip-3860). So 2 bytes are always enough, because even on pre-Shanghai (pre-EIP-3860) networks, EIP-170 would still cause the create opcode to revert (or the constructor to revert if only EIP-170 is enforced).

I spent some time chasing this lead during the contest myself, but found it invalid (at the time I didn't know about the Cantina finding). The confusion stems from forge PoCs working only due to how forge ignores the EVM creation and runtime size limits. 

The `Test` code below acts differently in different environments: `initTooBig` will revert if init code limit is enforced (49KB) and `runtimeTooBig` will revert if run time code limit is enforced (24KB). `initOk` and `runtimeOk` just show that the issue is due to size being over limit.
1. **Sepolia** :heavy_check_mark: :heavy_check_mark::  both fail (both limits enforced).
2. **RemixVM** :heavy_check_mark::x::  `initTooBig` fails, `runtimeTooBig` passes (run time code limit ignored).
3. **Forge** :x::x: : both `initTooBig` and  `runtimeTooBig` pass (both limits ignored). I've also found [this issue](https://github.com/foundry-rs/foundry/issues/4783) that explains this partially.


```solidity
pragma solidity 0.8.15;

contract Test {
    function initTooBig() external returns (address out) {
        bytes memory d = new bytes(50000);
        assembly{
            out:= create(0, d, mload(d))
        }
    }

    function initOk() external returns (address out) {
        bytes memory d = new bytes(48000);
        assembly{
            out:= create(0, d, mload(d))
        }
    }

    function runtimeTooBig() external returns (address out) {
        return address(new TooBig());
    }

    function runtimeOk() external returns (address out) {
        return address(new Ok());
    }

}

contract TooBig {
    constructor() {
        bytes memory d = new bytes(25000);
        assembly{
            return(d, mload(d))
        }
    }
}

contract Ok {
    constructor() {
        bytes memory d = new bytes(24000);
        assembly{
            return(d, mload(d))
        }
    }
}
```
